#!/bin/bash 
#
#SBATCH --job-name=indp
#SBATCH --partition=all
#SBATCH --account=mjm
#SBATCH --mem=20gb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=99:59:59
#SBATCH --output=/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/simulation_runs/indep/n_vs_alpha/indep_departure_n_trend_n_vs_alpha.log
#SBATCH --error=/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/simulation_runs/indep/n_vs_alpha/indep_departure_n_trend_n_vs_alpha.err


CONDA_BIN_PATH=/opt/miniconda/bin
ENV_NAME=mjm_env_gpu
ENV_PATH=/mnt/nas/users/$(whoami)/.conda/envs/$ENV_NAME
source $CONDA_BIN_PATH/activate $ENV_PATH

python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/simulation_runs/indep/n_vs_alpha/indep_departure_n_trend_n_vs_alpha.py
