#!/bin/bash 
#
#SBATCH --job-name=2d_var_conti
#SBATCH --partition=all
#SBATCH --account=mjm
#SBATCH --mem=10gb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --time=99:59:59
#SBATCH --output=/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/var_departure/conti_noise/d_trend/var_conti_2d.log
#SBATCH --error=/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/var_departure/conti_noise/d_trend/var_conti_2d.err
#SBATCH --nodelist=cpu-compute

CONDA_BIN_PATH=/opt/miniconda/bin
ENV_NAME=mjm_env_gpu
ENV_PATH=/mnt/nas/users/$(whoami)/.conda/envs/$ENV_NAME
source $CONDA_BIN_PATH/activate $ENV_PATH

python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/var_departure/conti_noise/d_trend/var_conti_2d.py