#!/bin/bash
#SBATCH --job-name=mjm_env_cpu
#SBATCH --nodes=1
#SBATCH --mem=4gb
#SBATCH --partition=all
#SBATCH --gres=gpu:1
#SBATCH --nodelist=gpu-compute
#SBATCH --output=/mnt/nas/users/mjm/GitHub/private_conti_test/kernel_test/testEnv.log
#SBATCH --error=/mnt/nas/users/mjm/GitHub/private_conti_test/kernel_test/testEnv.err
CONDA_BIN_PATH=/opt/miniconda/bin
ENV_NAME=mjm_env_gpu #local에서와 같은 이름으로 입력
ENV_PATH=/mnt/nas/users/$(whoami)/.conda/envs/$ENV_NAME
#$CONDA_BIN_PATH/conda env remove --prefix $ENV_PATH #env가 이미 존재하면 삭제
#$CONDA_BIN_PATH/conda create -y --prefix $ENV_PATH python=3.8
source $CONDA_BIN_PATH/activate $ENV_PATH
conda install -y scikit-learn theano matplotlib scipy numpy