#!/bin/bash 
#
#SBATCH --job-name=a_dsc
#SBATCH --partition=all
#SBATCH --account=mjm
#SBATCH --mem=20gb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=99:59:59
#SBATCH --output=/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a_trend_disc_jobs.log
#SBATCH --error=/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a_trend_disc_jobs.err
#SBATCH --gres=gpu:1
#SBATCH --nodelist=gpu-compute

CONDA_BIN_PATH=/opt/miniconda/bin
ENV_NAME=mjm_env_gpu
ENV_PATH=/mnt/nas/users/$(whoami)/.conda/envs/$ENV_NAME
source $CONDA_BIN_PATH/activate $ENV_PATH

python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a01_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a02_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a03_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a04_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a05_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a06_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a07_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a08_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a09_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a10_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a11_10000_dsc.py
python -u /mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/mean_departure/disc_noise/alpha_trend/a12_10000_dsc.py
