#!/bin/bash 
#
#SBATCH --job-name=copula2d_10000
#SBATCH --partition=all
#SBATCH --account=mjm
#SBATCH --mem=100gb
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=25
#SBATCH --time=999:59:59
#SBATCH --output=/mnt/nas/users/mjm/GitHub/private_conti_test/R_implm/simulations/copula_2d/n_trend/copula2d_10000.log
#SBATCH --error=/mnt/nas/users/mjm/GitHub/private_conti_test/R_implm/simulations/copula_2d/n_trend/copula2d_10000.err
#SBATCH --nodelist=cpu-compute

Rscript n_trend_10000.R